version: '3.9'
services:
  postgresdb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockerBDcalendario
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - redApiFestivos

networks:
  redApiFestivos:
    driver: bridge
